# Readest-specific cloud/reader adapter and fixtures; the device runtime is shared.
add_library(simulator-https OBJECT "${CMAKE_CURRENT_SOURCE_DIR}/src/http.cpp")
target_compile_definitions(simulator-https PRIVATE READEST_SIMULATOR_TRANSPORT)
target_link_libraries(readest-sync PRIVATE simulator-https pocketbook-simulator)
target_include_directories(readest-sync PRIVATE "${READEST_SIM_DIR}")
target_compile_definitions(readest-sync PRIVATE READEST_SIMULATOR)
find_package(Python3 REQUIRED COMPONENTS Interpreter)
add_custom_command(OUTPUT "${CMAKE_BINARY_DIR}/fixtures/ready"
  COMMAND Python3::Interpreter "${READEST_SIM_DIR}/fixtures.py" "${CMAKE_BINARY_DIR}/fixtures"
  DEPENDS "${READEST_SIM_DIR}/fixtures.py" "${CMAKE_CURRENT_SOURCE_DIR}/tools/package_probe.py")
add_custom_target(simulator-fixtures DEPENDS "${CMAKE_BINARY_DIR}/fixtures/ready")
add_dependencies(readest-sync simulator-fixtures)
target_compile_definitions(readest-sync PRIVATE READEST_SIM_FIXTURES="${CMAKE_BINARY_DIR}/fixtures")
target_sources(qt-ui-test PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/src/http.cpp")
add_executable(simulator-test "${READEST_SIM_DIR}/test.cpp" ${PRESENTATION_SOURCES} ${DEVICE_SOURCE} "${CMAKE_CURRENT_SOURCE_DIR}/qml/readest.qrc")
target_compile_definitions(simulator-test PRIVATE READEST_DESKTOP READEST_SIMULATOR READEST_TEST_CONTROLS="${POCKETBOOK_SIM_CONTROLS}" READEST_SIM_FIXTURES="${CMAKE_BINARY_DIR}/fixtures")
target_include_directories(simulator-test PRIVATE "${READEST_SIM_DIR}")
target_link_libraries(simulator-test PRIVATE pocketbook-simulator simulator-https readest-core Qt6::Quick Qt6::Qml Qt6::Gui Qt6::Core)
add_dependencies(simulator-test simulator-fixtures)
add_test(NAME simulator COMMAND simulator-test)
set_tests_properties(simulator PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen;QT_QUICK_BACKEND=software")
set_property(TEST simulator APPEND PROPERTY ENVIRONMENT "POCKETBOOK_SIM_CLOUD=mock")
add_test(NAME simulator-real COMMAND Python3::Interpreter "${READEST_SIM_DIR}/live_test.py" $<TARGET_FILE:simulator-test>)
set_tests_properties(simulator-real PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen;QT_QUICK_BACKEND=software;POCKETBOOK_SIM_CLOUD=real")
