#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

DEVICE_MOUNT="${DEVICE_MOUNT:-/Volumes/PB743G}"
EXPECTED_FIRMWARE="U743g.6.11.1683"
SCREEN_DIR="$DEVICE_MOUNT/screens"
CAPTURE_ID="$(date '+%Y%m%d-%H%M%S')"
OUTPUT_DIR="${CAPTURE_OUTPUT_DIR:-/private/tmp/pocketbook-ui-capture-$CAPTURE_ID}"
BASELINE_FILE="$(mktemp -t pocketbook-ui-baseline.XXXXXX)"
FOCUS_NOTES=""
LANDSCAPE_NOTES=""
GHOSTING_NOTES=""

cleanup() {
  rm -f "$BASELINE_FILE"
}
trap cleanup EXIT

take_screenshot() {
  step "Open Task Manager from the center icon in the top status bar, then tap 'Take a screenshot'."
  note "Do not hold Home here: on firmware 6.11.1683 it can dismiss transient surfaces first."
  pause "Press Enter after the screenshot has been saved."
}

require_device() {
  if [[ ! -d "$SCREEN_DIR" ]]; then
    warn "PocketBook screenshot directory not found at $SCREEN_DIR"
    say "Reconnect and unlock the device, then re-run with DEVICE_MOUNT=/path if needed."
    exit 1
  fi
}

wait_for_device() {
  while [[ ! -d "$SCREEN_DIR" ]]; do
    warn "PocketBook screenshot directory not found at $SCREEN_DIR"
    pause "Select PC link on the device, then press Enter after it appears in Finder."
  done
}

banner "PocketBook 6.11 native UI capture"

stage "Verify device and establish the baseline"
require_device
FIRMWARE=$(grep -E '^latest_version=' "$DEVICE_MOUNT/system/config/global.cfg" | tail -n1 | cut -d= -f2- || true)
if [[ "$FIRMWARE" != "$EXPECTED_FIRMWARE" ]]; then
  warn "Expected $EXPECTED_FIRMWARE, found ${FIRMWARE:-unknown}."
  exit 1
fi
find "$SCREEN_DIR" -maxdepth 1 -type f -name 'scr*.bmp' -print | sort > "$BASELINE_FILE"
say "Verified InkPad 4 firmware $FIRMWARE."
say "Recorded $(wc -l < "$BASELINE_FILE" | tr -d ' ') existing screenshot(s)."
warn "Use a generic book where possible. Avoid account details and private library titles."
step "Eject PB743G in Finder, disconnect USB, and keep the device in portrait orientation."
pause "Press Enter when the normal PocketBook interface is visible."

stage "Capture the native Library detailed list"
step "Open Library and select the native detailed/list view."
step "Show several rows with title, author, progress, and status indicators visible."
take_screenshot

stage "Capture Library menus"
step "Open the Library's main menu with sort, filter, search, and view controls visible."
take_screenshot
step "Close it, then long-press a generic book until its context menu appears."
take_screenshot

stage "Capture book information and a dialog"
step "Open the generic book's information/details page."
take_screenshot
step "Trigger a harmless native confirmation dialog, such as delete/remove, without confirming it."
take_screenshot
step "Cancel the dialog and return to Library."

stage "Capture text input and keyboard"
step "Open Library search and focus the text field so the on-screen keyboard is visible."
step "Enter 'Sample' so text, cursor, keyboard, and clear/search controls are visible."
take_screenshot
step "If a validation error can be shown without changing data, capture it too; otherwise skip it."
if confirm "Did you display a validation error?"; then
  take_screenshot
fi

stage "Record hardware navigation and focus"
step "Dismiss the keyboard and use the page buttons to move through Library."
step "Use Home, Menu, and Back once each; note what receives focus or changes."
step "If a visible focus state appears, leave it visible and take a screenshot."
if confirm "Is a visible focus state currently shown?"; then
  take_screenshot
fi
ask FOCUS_NOTES "Briefly describe button behavior and visible focus:"

stage "Capture landscape behavior"
step "Enable the G-sensor, rotate the device, and return to the native Library detailed/list view."
if confirm "Did the native Library rotate to landscape?"; then
  take_screenshot
  step "Open the Library menu in landscape."
  take_screenshot
  step "Open the generic book's information/details page in landscape."
  take_screenshot
  ask LANDSCAPE_NOTES "Briefly describe reflow, clipping, or preserved scroll position:"
  step "Return the device to portrait orientation."
else
  LANDSCAPE_NOTES="The native Library remained in portrait with the G-sensor enabled; no landscape reflow occurred."
  say "$LANDSCAPE_NOTES"
fi

stage "Observe E Ink refresh and import the evidence"
step "In Library, page rapidly five times, open and close a menu twice, then wait for a full refresh."
ask GHOSTING_NOTES "Describe ghosting, flashes, partial refreshes, and recovery:"
step "Take one final screenshot if any residual ghosting is visible."
if confirm "Is residual ghosting visible?"; then
  take_screenshot
fi
step "Reconnect PB743G over USB and wait for it to mount in Finder."
pause "Press Enter when PB743G is mounted."
wait_for_device

CURRENT_FILE="$(mktemp -t pocketbook-ui-current.XXXXXX)"
NEW_FILE="$(mktemp -t pocketbook-ui-new.XXXXXX)"
trap 'rm -f "$BASELINE_FILE" "$CURRENT_FILE" "$NEW_FILE"' EXIT
find "$SCREEN_DIR" -maxdepth 1 -type f -name 'scr*.bmp' -print | sort > "$CURRENT_FILE"
comm -13 "$BASELINE_FILE" "$CURRENT_FILE" > "$NEW_FILE"
NEW_COUNT=$(wc -l < "$NEW_FILE" | tr -d ' ')
if [[ "$NEW_COUNT" -eq 0 ]]; then
  warn "No new screenshots found. They may not have saved or the device mounted elsewhere."
  exit 1
fi

mkdir -p "$OUTPUT_DIR/screens"
MANIFEST="$OUTPUT_DIR/README.md"
{
  printf '# PocketBook InkPad 4 native UI capture\n\n'
  printf -- "- Firmware: \`%s\`\n" "$FIRMWARE"
  printf -- "- Captured: \`%s\`\n" "$(date '+%Y-%m-%d %H:%M:%S %Z')"
  printf -- '- Resolution expected: 1404 x 1872 portrait\n'
  printf -- "- New screenshots: \`%s\`\n\n" "$NEW_COUNT"
  printf '## Observation notes\n\n'
  printf '**Hardware navigation and focus:** %s\n\n' "${FOCUS_NOTES:-Not recorded}"
  printf '**Landscape behavior:** %s\n\n' "${LANDSCAPE_NOTES:-Not recorded}"
  printf '**E Ink refresh and ghosting:** %s\n\n' "${GHOSTING_NOTES:-Not recorded}"
  printf '## Files\n\n'
} > "$MANIFEST"

while IFS= read -r source; do
  name=$(basename "$source" .bmp)
  bmp_target="$OUTPUT_DIR/screens/$name.bmp"
  png_target="$OUTPUT_DIR/screens/$name.png"
  cp "$source" "$bmp_target"
  if command -v sips >/dev/null 2>&1; then
    sips -s format png "$bmp_target" --out "$png_target" >/dev/null
  else
    warn "sips not found; kept BMP only for $name."
  fi
  checksum=$(shasum -a 256 "$bmp_target" | awk '{print $1}')
  printf -- "- \`%s.bmp\` - SHA-256 \`%s\`\n" "$name" "$checksum" >> "$MANIFEST"
done < "$NEW_FILE"

say "Imported $NEW_COUNT new screenshot(s)."
say "Evidence package: $OUTPUT_DIR"
say "Review every image for private content before copying it into the repository."

finish
